//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIACHIGH
    {
        public int MADIACHI { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public string HOTEN { get; set; }
        public int SDT { get; set; }
        public string SONHA { get; set; }
        public string PHUONG { get; set; }
        public string QUAN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
