//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MAHOADON { get; set; }
        public int MAKHUYENMAI { get; set; }
        public int MANHANVIEN { get; set; }
        public int MAKHACHHANG { get; set; }
        public int MATINHTRANGDON { get; set; }
        public double TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYGIO { get; set; }
        public double TONGTHUE { get; set; }
        public string GHICHU { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
