//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string HinhAnh { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> Thue { get; set; }
        public string MoTa { get; set; }
    }
}
