//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int MANHANVIEN { get; set; }
        public string TENNV { get; set; }
        public Nullable<int> SDT { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
    }
}
