//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADON = new HashSet<HOADON>();
        }

        [Required(ErrorMessage = "ID not emty")]
        public int MANHANVIEN { get; set; }
        [Required(ErrorMessage = "Name not emty")]
        public string TENNV { get; set; }
        [Required(ErrorMessage = "Phone not emty")]
        public Nullable<int> SDT { get; set; }
        [Display(Name = "Email ")]
        [Required(ErrorMessage = "Email not emty")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string EMAIL { get; set; }

        [Display(Name = "Mật khẩu ")]
        [Required(ErrorMessage = "Password not emty")]
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
    }
}
